# Generated by Django 5.0.4 on 2024-04-22 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorianApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurerValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dorianApp.categorymaster')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dorianApp.lobmaster')),
            ],
        ),
    ]
