# Generated by Django 5.0.4 on 2024-04-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorianApp', '0002_insurervalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurervalue',
            old_name='Year',
            new_name='year',
        ),
    ]
